import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import ComponentCard from "@/components/common/ComponentCard";
import PageBreadcrumb from "@/components/common/PageBreadCrumb";
import PageMeta from "@/components/common/PageMeta";
import Button from "@/components/ui/button/Button";
import { BoxIcon } from "@/icons";
export default function Buttons() {
    return (_jsxs("div", { children: [_jsx(PageMeta, { title: "React.js Buttons Dashboard | TailAdmin - React.js Admin Dashboard Template", description: "This is React.js Buttons Dashboard page for TailAdmin - React.js Tailwind CSS Admin Dashboard Template" }), _jsx(PageBreadcrumb, { pageTitle: "Buttons" }), _jsxs("div", { className: "space-y-5 sm:space-y-6", children: [_jsx(ComponentCard, { title: "Primary Button", children: _jsxs("div", { className: "flex items-center gap-5", children: [_jsx(Button, { size: "sm", variant: "primary", children: "Button Text" }), _jsx(Button, { size: "md", variant: "primary", children: "Button Text" })] }) }), _jsx(ComponentCard, { title: "Primary Button with Leading Icon", children: _jsxs("div", { className: "flex items-center gap-5", children: [_jsx(Button, { size: "sm", variant: "primary", startIcon: _jsx(BoxIcon, { className: "size-5" }), children: "Button Text" }), _jsx(Button, { size: "md", variant: "primary", startIcon: _jsx(BoxIcon, { className: "size-5" }), children: "Button Text" })] }) }), _jsx(ComponentCard, { title: "Primary Button with Trailing Icon", children: _jsxs("div", { className: "flex items-center gap-5", children: [_jsx(Button, { size: "sm", variant: "primary", endIcon: _jsx(BoxIcon, { className: "size-5" }), children: "Button Text" }), _jsx(Button, { size: "md", variant: "primary", endIcon: _jsx(BoxIcon, { className: "size-5" }), children: "Button Text" })] }) }), _jsx(ComponentCard, { title: "Secondary Button", children: _jsxs("div", { className: "flex items-center gap-5", children: [_jsx(Button, { size: "sm", variant: "outline", children: "Button Text" }), _jsx(Button, { size: "md", variant: "outline", children: "Button Text" })] }) }), _jsx(ComponentCard, { title: "Outline Button with Leading Icon", children: _jsxs("div", { className: "flex items-center gap-5", children: [_jsx(Button, { size: "sm", variant: "outline", startIcon: _jsx(BoxIcon, { className: "size-5" }), children: "Button Text" }), _jsx(Button, { size: "md", variant: "outline", startIcon: _jsx(BoxIcon, { className: "size-5" }), children: "Button Text" })] }) }), " ", _jsx(ComponentCard, { title: "Outline Button with Trailing Icon", children: _jsxs("div", { className: "flex items-center gap-5", children: [_jsx(Button, { size: "sm", variant: "outline", endIcon: _jsx(BoxIcon, { className: "size-5" }), children: "Button Text" }), _jsx(Button, { size: "md", variant: "outline", endIcon: _jsx(BoxIcon, { className: "size-5" }), children: "Button Text" })] }) })] })] }));
}
